services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MonduPayment\Settings\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\MonduPayment\Settings\Service\ModuleSettingsService
    public: true
